# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TpT03cSPqAJo1k_KOJL4DW-FLUZzZkuA
"""

import numpy as np  
import pandas as pd  
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

df=pd.read_csv('/content/IPL_Sold_players_2013_23.csv')
df.head(10)

df.info()

"""REMOVING COMMA (,) IN PRICE"""

df['Price']=df['Price'].apply(lambda x: str(x).replace(',','')).astype('float')

"""No. of unique value"""

for col in df.columns:
    print('No.of Unique values in',col,'are',df[col].nunique())

"""FEATURE ENGINEERING"""

df['Type'].unique()

"""REPLACING DIFFERNT NAME TO UNIQUE NAMES"""

df['Type']=df['Type'].apply(lambda x: x.replace('Batter ','Batsman'))
df['Type']=df['Type'].apply(lambda x: x.replace('Batsman ','Batsman'))
df['Type']=df['Type'].apply(lambda x: x.replace('All-Rounder ','All-Rounder'))
df['Type']=df['Type'].apply(lambda x: x.replace(' All-Rounder ','All-Rounder'))
df['Type']=df['Type'].apply(lambda x: x.replace(' All-Rounder','All-Rounder'))
df['Type']=df['Type'].apply(lambda x: x.replace('Bowler ','Bowler'))
df['Type']=df['Type'].apply(lambda x: x.replace(' Bowler ','Bowler'))
df['Type']=df['Type'].apply(lambda x: x.replace(' Bowler','Bowler'))
df['Type']=df['Type'].apply(lambda x: x.replace('Wicket-Keeper ','Wicket-Keeper'))
df['Type']=df['Type'].apply(lambda x: x.replace('Wicket Keeper ','Wicket-Keeper'))
df['Type']=df['Type'].apply(lambda x: x.replace(' Wicket Keeper','Wicket-Keeper'))
df['Type']=df['Type'].apply(lambda x: x.replace('Wicket Keeper','Wicket-Keeper'))

df['Type'].unique()

df.duplicated().sum()

df['Nationality'].value_counts()

for col in df.columns:
    print('No.of Null values in',col,'are',df[col].isnull().sum() )

df.groupby('Nationality')['Price'].mean()

"""OVERSEAS PLAYERS GETTING HIGH PAY COMPARED TOOUR INDIAN PLAYERS"""

df['Nationality']=df['Nationality'].apply(lambda x:'na' if "Not Available" in x else x)

"""**DATA VISUALISATION**
SWARMPLOT IS LIKE SCATTER PLOT SO, WE CAN OBSERVE HOW DATA POINTS ARE DISTRIBUTED
"""

sns.swarmplot(x="Nationality", y="Price", data=df)

df=df.sort_values(by='Price',ascending=False)
df.head(10)

"""THESE ARE THE TOP 10 PAID PLAYERS IN IPL

SAM CURRAN IS THE HIGHEST PAID PLAYER IN IPL HISTORY FROM 2013 TO 2023
"""

df.groupby('Type')['Price'].mean()

"""WICKET KEEPERS AND ALL ROUNDERS ARE GETTING NEARLY EQUAL AMOUNT OF AVERAGE PAY of 2 CRORES"""

top_10_paid=(df.groupby('Name')['Price'].mean().sort_values(ascending=False)).head(10)
top_10_paid

fig=px.bar(x=top_10_paid.index,
           y= top_10_paid.values,
           color= top_10_paid.index,
           text= top_10_paid.values,
           title=' Top_paid_Cricketers')
fig.update_layout(xaxis_title='Players',yaxis_title='Amount')

features=['Name','Nationality','Type','Team']
for feature in features:
    Continents_population=df.groupby(by=feature)['Price'].mean().sort_values(ascending=False).head(7)
    fig=px.bar(x=Continents_population.index,
           y=Continents_population.values,
           color=Continents_population,
           text=Continents_population.values,
           color_discrete_sequence=px.colors.sequential.PuBu,
          template='plotly_dark')
    fig.update_layout(xaxis_title=feature,yaxis_title='Payment paid')
    fig.show()

"""WE CAN ANALSE

1)FOREIGN PLAYERS PAID HIGH COMPARED TO INDIAN PLAYERS

2)BOWLERS ARE GETTING LOW PAY COMPARING TO REMAINING

3)PUNJAB KINGS UTILISED MOST OF IT'S MONEY ON PLAYERS
"""

lowest_paid_players=(df.groupby('Name')['Price'].mean().sort_values(ascending=True)).head(10)
lowest_paid_players

fig=px.bar(x=lowest_paid_players.index,
           y= lowest_paid_players.values,
           color= lowest_paid_players.index,
           text= lowest_paid_players.values,
           title=' lowest_paid_players')
fig.update_layout(xaxis_title='Players',yaxis_title='Amount')